name: Hello Github Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env: 
      COURSE: CloudComputing
    steps:
      - name: Say hello
        run: echo "Hello From ${COURSE}"
      - run: echo “I’ll list files.”
      - run: ls -al
